version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers

    steps:
      - checkout

      - run:
          name: Print the Current Time 1
          command: date

      - run: apt-get update && apt-get -y install gettext-base
      - run: cp .env.example .env
      - run: export $(cat .env | grep -v ^# | xargs)
      - run: ./setup.sh 
      - run: docker-compose build --pull
      - run: docker-compose run --rm dev ng test --browsers Chrome_no_sandbox -w false 

      - run:
          name: Print the Current Time 2
          command: date