version: 2
jobs:
  build:
    working_directory: ~/project1
    docker:
      - image: circleci/node:9.4.0-browsers
    steps:
      - checkout
      - setup_remote_docker
      - run: pwd
      - run: ls -l ~/project1
      - run:
          name: Build
          command: docker-compose build && docker run --rm -v /home/circleci/project1:/opt/app teracy/angular-boilerplate:dev_develop pwd && ls ./node_modules/@angular && ls ./node_modules/@angular-cli ./node_modules/ && sh ./node_modules/@angular/cli/bin/ng test --browsers Chrome_no_sandbox -w false

