version: 2
jobs:
  build:
    working_directory: ~/project1
    docker:
      - image: circleci/node:8.9.3-browsers
    dependencies:
      pre:
        - npm install angular-cli@latest -g
    steps:
      - checkout

      - run: npm install
 

      - run: npm run ng -- version
      - run: npm run ng -- update @angular/cli
      - run: xvfb-run -a npm run test

