version: 2
jobs:
  build:
    docker:
      - image: alpine:3.6

    steps:
      - checkout

      - run:
          name: Print the Current Time 1
          command: date

      - run: apk add --update libintl && apk add --virtual build_deps gettext
      - run: cp .env.example .env
      - run: export $(cat .env | grep -v ^# | xargs)
      - run: ./setup.sh 
      - run: docker-compose build --pull
      - run: docker-compose run --rm dev ng test --browsers Chrome_no_sandbox -w false 

      - run:
          name: Print the Current Time 2
          command: date