version: 2
jobs:
  build:
    working_directory: ~/project1
    docker:
      - image: circleci/node:9.4.0-browsers
    steps:
      - checkout
      # - setup_remote_docker
      - run: pwd && cat .angular-cli.json
      - run: ls -l ~/project1

      - run: yarn install

      - run: xvfb-run -a npm run test -- --single-run --no-progress

