version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.4.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Start container
          command: docker-compose up --build
      - run:
          name: Test
          command: docker-compose run --rm dev ng test --browsers Chrome_no_sandbox -w false 

