version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.4.0-browsers
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build
          command: docker-compose build --pull
      - run:
          name: Test
          command: docker-compose run --rm -v $(pwd):/opt/app dev yarn test

