version: 2
jobs:
  build:
    working_directory: ~/project1
    docker:
      - image: circleci/node:9.4.0-browsers
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build
          command: docker-compose build --pull
      - run: pwd
      - run: ls
      - run:
          name: Test
          command: docker-compose run --rm -v $(pwd):/opt/app dev ls -l && bash -c "yarn run test"

